<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="vikpc" failures="2" tests="6" name="BankingAppTest" time="164.082" errors="0" timestamp="2022-11-01T22:22:06 IST">
  <testcase classname="com.inetBanking.testCases.TC_loginTest_001" name="loginTest" time="4.838"/>
  <testcase classname="com.inetBanking.testCases.TC_loginTest_002" name="loginDDT" time="20.676"/>
  <testcase classname="com.inetBanking.testCases.TC_loginTest_002" name="loginDDT" time="12.902">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.inetBanking.testCases.TC_loginTest_002.loginDDT(TC_loginTest_002.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetBanking.testCases.TC_loginTest_002" name="loginDDT" time="21.933"/>
  <testcase classname="com.inetBanking.testCases.TC_loginTest_002" name="loginDDT" time="10.855">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.inetBanking.testCases.TC_loginTest_002.loginDDT(TC_loginTest_002.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetBanking.testCases.TC_AddCustomerTest_003" name="addNewCustomer" time="26.068"/>
</testsuite> <!-- BankingAppTest -->
